### ISSUE TITLE
@megalo/target@0.5.0 模板使用 pug 报错

### ISSUE THREAD

**Issue by b2nil** [kaola-fed/megalo-aot#39]
megalo-cli 新创建的项目，将 @megalo/target 升级到 v0.5.0 后，使用 pug 报错。

pug 模板： 
```
<template lang="pug">
  div.app
    img.img(:src="logo" @touchstart="changeStat")
    hello-world(:msg="acc" :color="color")
</template>
```
webpack 配置：
- 需安装依赖 `pug`, `pug-plain-loader`
```javascript
{
    test: /\.pug$/,
    oneOf: [  // this applies to `<template lang="pug">` in Vue components
             {
	        resourceQuery: /^\?vue/,
	        use: [ 'pug-plain-loader' ]
            }
        ]
},
```

错误如下：
```bash
ERROR in ./src/pages/hello.vue?vue&type=template&id=4bcda7fe&scoped=true&lang=pug& (./node_modules/@megalo/target/lib/frameworks/vue/loader/template.js??vue-loader-options!./node_modules/@megalo/target/lib/frameworks/vue/loader/selector.js??vue-loader-options!./node_modules/pug-plain-loader!./src/pages/hello.vue?vue&type=template&id=4bcda7fe&scoped=true&lang=pug&)
Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: E:\vueprojects\pugcheck\src\pages\hello.vue:11:17
    9| import HelloWorld from "@/components/HelloWorld.vue";
    10| export default {
  > 11|     components: {
------------------------^
    12|         HelloWorld
    13|     },
    14|     data() {

unexpected text "{
   "
    at makeError (E:\vueprojects\pugcheck\node_modules\pug-error\index.js:32:13)
    at Lexer.error (E:\vueprojects\pugcheck\node_modules\pug-lexer\index.js:59:15)
    at Lexer.fail (E:\vueprojects\pugcheck\node_modules\pug-lexer\index.js:1441:10)
    at Lexer.advance (E:\vueprojects\pugcheck\node_modules\pug-lexer\index.js:1501:15)
    at Lexer.callLexerFunction (E:\vueprojects\pugcheck\node_modules\pug-lexer\index.js:1456:23)
    at Lexer.getTokens (E:\vueprojects\pugcheck\node_modules\pug-lexer\index.js:1512:12)
    at lex (E:\vueprojects\pugcheck\node_modules\pug-lexer\index.js:12:42)
    at Object.lex (E:\vueprojects\pugcheck\node_modules\pug\lib\index.js:99:27)
    at Function.loadString [as string] (E:\vueprojects\pugcheck\node_modules\pug-load\index.js:44:24)
    at compileBody (E:\vueprojects\pugcheck\node_modules\pug\lib\index.js:86:18)
    at Object.exports.compile (E:\vueprojects\pugcheck\node_modules\pug\lib\index.js:242:16)
    at Object.module.exports (E:\vueprojects\pugcheck\node_modules\pug-plain-loader\index.js:11:24)
 @ ./src/pages/hello.vue?vue&type=template&id=4bcda7fe&scoped=true&lang=pug& 1:0-310 1:0-310
 @ ./node_modules/vue-loader/lib??vue-loader-options!./src/pages/hello.vue
 @ ./src/pages/hello.vue
```

**Comment by b2nil** [comment]
这个 bug 有什么进展吗？

**Comment by fengzilong** [comment]
因为内部实现的方式，比较难解决...不过应该是有办法可以解决的，这两天正在看

**Comment by fengzilong** [comment]
@b2nil 试下升级到 @megalo/target@0.5.1

**Comment by b2nil** [comment]
Thanks, it's working now!
